name: Java CI with Gradle

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
    name: Java ${{ matrix.java }} setup

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        
        with:
          java-version: ${{ matrix.java }}
          
      - name: Build
        run: ./gradlew classes
      
      - name: Test
        run: ./gradlew test jacocoTestReport
        env:
          API_KEY: ${{ secrets.API_KEY }}
