name: Java CI with Gradle

on:
  push:
    branches: 
      - master
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Build
        run: ./gradlew classes
      
      - name: Test
        run: ./gradlew test jacocoTestReport
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: SonarQube
        run: ./gradlew sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
